// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnngfsixbqdjepjfdiln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubmdmc2l4YnFkamVwamZkaWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NzM1OTIsImV4cCI6MjA5MDE0OTU5Mn0.zv9nROgg-ze_fTQsaDxpNI-G-ag11RpDgQchICzXw1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});